### ISSUE TITLE
Watchtower vs mammons

### ISSUE THREAD

**Issue by Romboter** [olted/aedilebot#9]
So the bot is back to saying its 2 mammon's to kill a watchtower in the latest release which is what the data mine says, but we all know it actually takes 3 cuz devman does fuzzy maths lol

Was the previous version just fudging the watchtower hp to 361 or something?

**Comment by olted** [comment]
The reason is because devman actually has fucked calculations for projectile damage. HEs are a projectile and assuming they do 240*0.75 = 180 damage per mammon, and a watchtower has 350hp, it should only take 2. This is all mathematically sound. However; for some reason in game in reality HEs only do 95% of their real base damage because theyre projectiles. Anyway for the purposes of the bot I've changed the mammon damage to what it actually does in-game to represent that; should work now.

**Comment by Romboter** [comment]
Ok, follow up here with this data I didn't previously know about projectiles.
Should a new function be put into the bot to apply this 95% to more projectiles vs adjusting weapon dmg?

Here is another example where it applies I believe, RPG vs rile pillbox.
RPG: 550 dmg
Rifle pill: 400 hp
Mitigation:  .25
Post mitigation dmg: 412.5
Post 95% dmg: 392 (rounded up)

Without the 95% bot says 1 shot
After applying the 95% 2 shots, which in-game is real.
